### ISSUE TITLE
Optimize job fetching.

### ISSUE THREAD

**Issue by ckline-tryptic** [openstax/corgi#522]
## Description
Currently CORGI fetches all 365 previous days of jobs every 10 seconds, this is obviously inefficient.

## Details
In order to reduce the load we will split it into 2 queries. 
1. Page loads, fetch all jobs from last 365 days.
2. Update jobs, fetch all jobs from last x hours or minutes.

## Tasks
- [ ] Add time query params to [this endpoint](https://github.com/openstax/corgi/blob/754dee706e4fbaeef4cbade1c04622704de93857/backend/app/app/api/endpoints/jobs.py#L20)
- [ ] Update [the Jobs store](https://github.com/openstax/corgi/blob/bbe24df796a96e43c989a418f69464e24e5f4485/frontend/src/ts/stores.ts#L11-L32) to use the new url, add new logic to combine the new list into the old one, and add a way to initialize the store with all the jobs
- [ ] Update tests

**Comment by ckline-tryptic** [comment]
## Given
corgi client has no jobs locally yet
## When
corgi polls for jobs 
## Then
it pulls all the jobs.

## Given
corgi client has jobs locally
## When
corgi polls for jobs
## Then
it pulls only the jobs after the oldest currently running in the last 24hrs

**Comment by omehes** [comment]
verified in local setup and on corgi prod.
job times are updated only for the latest jobs (witihn 24h)
